@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":EditPropertyCommandParser" as EditPropertyCommandParser LOGIC_COLOR
participant "command:EditPropertyCommand" as EditPropertyCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("editprop 1 n/Skyview")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("editprop 1 n/Skyview")
activate AddressBookParser

create EditPropertyCommandParser
AddressBookParser -> EditPropertyCommandParser :
activate EditPropertyCommandParser

EditPropertyCommandParser --> AddressBookParser
deactivate EditPropertyCommandParser

AddressBookParser -> EditPropertyCommandParser : parse("1 n/Skyview")
activate EditPropertyCommandParser

create EditPropertyCommand
EditPropertyCommandParser -> EditPropertyCommand :
activate EditPropertyCommand

EditPropertyCommand --> EditPropertyCommandParser : command
deactivate EditPropertyCommand

EditPropertyCommandParser --> AddressBookParser : command
deactivate EditPropertyCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
EditPropertyCommandParser -[hidden]-> AddressBookParser
destroy EditPropertyCommandParser

AddressBookParser --> LogicManager : command
deactivate AddressBookParser

LogicManager -> EditPropertyCommand : execute()
activate EditPropertyCommand

EditPropertyCommand -> EditPropertyCommand : createEditedProperty(propertyToEdit, editPropertyDescriptor)
activate EditPropertyCommand
EditPropertyCommand --> EditPropertyCommand : editedProperty
deactivate EditPropertyCommand

EditPropertyCommand -> Model : setProperty(PropertyToEdit, editedProperty)

EditPropertyCommand -> Model : updateFilteredPropertyList(PREDICATE_SHOW_ALL_PROPERTIES)

create CommandResult
EditPropertyCommand -> CommandResult : new CommandResult("Edited property: " + editedProperty)
activate CommandResult

CommandResult --> EditPropertyCommand
deactivate CommandResult

EditPropertyCommand --> LogicManager : commandResult
deactivate EditPropertyCommand

[<--LogicManager : commandResult
deactivate LogicManager
@enduml
