@startuml
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12

package PropertyObjectDiagram {
    Object "<u>:Property" as Property {
    }

    Object "<u>:PropName" as PropName {
    }
    Object "<u>:PropAddress" as PropAddress {
    }
    Object "<u>:PropPhone" as PropPhone {
    }
    Object "<u>:Price" as Price {
    }
    Object "<u>:Tags" as Tags {
    }
}

PropName <-- Property : has <
PropAddress <-- Property : has <
PropPhone <-- Property : has <
Price <-- Property : has <
Tags <-- Property : has <

@enduml
